site_name: "Engineering Fundamentals"
site_url: ""

docs_dir: docs

theme:
  name: "material"
  features:
    - navigation.sections
    - navigation.indexes
    - content.code.copy
    - content.tabs.link
    - navigation.footer
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: amber
      toggle:
        icon: material/white-balance-sunny
        name: Switch to light mode

nav:
  - Home: index.md
#  - Test:
#    - Module 0.1 - Test:
#      - Overview: c0-test/m1-test/overview.md
#      - Theory: c0-test/m1-test/theory.md
#      - Quiz: c0-test/m1-test/quiz.md
#      - Demo: c0-test/m1-test/demo.md
#      - Plotting Demo: c0-test/m1-test/plot-demo.md
#      - Python Shell: c0-test/m1-test/repl.md
  - Signals and Systems:
    - Module 1.1 - Intro to Signals and Systems:
      - Overview: c1-signals-and-systems/m1-intro-to-signals-and-systems/00-overview.md
      - Chapter 1 - What is a Signal?:
        - Introduction: c1-signals-and-systems/m1-intro-to-signals-and-systems/01-what-is-a-signal/00-intro.md
        - Types of Signals: c1-signals-and-systems/m1-intro-to-signals-and-systems/01-what-is-a-signal/01-types.md
        - Quiz: c1-signals-and-systems/m1-intro-to-signals-and-systems/01-what-is-a-signal/02-quiz.md
      - Chapter 2 - Signal Properties:
        - Introduction: c1-signals-and-systems/m1-intro-to-signals-and-systems/02-signal-properties/00-intro.md
        - "Periodicity: Definition": c1-signals-and-systems/m1-intro-to-signals-and-systems/02-signal-properties/01-periodicity.md
        - "Periodicity: WE1": c1-signals-and-systems/m1-intro-to-signals-and-systems/02-signal-properties/02-periodicity-we01.md
        - "Periodicity: WE2": c1-signals-and-systems/m1-intro-to-signals-and-systems/02-signal-properties/03-periodicity-we02.md
        - "Periodicity: Quiz": c1-signals-and-systems/m1-intro-to-signals-and-systems/02-signal-properties/04-periodicity-quiz.md
        - "Symmetry: Definition": c1-signals-and-systems/m1-intro-to-signals-and-systems/02-signal-properties/05-symmetry.md
        - "Symmetry: WE1": c1-signals-and-systems/m1-intro-to-signals-and-systems/02-signal-properties/06-symmetry-we01.md
      - Chapter 3 - Energy and Power: c1-signals-and-systems/m1-intro-to-signals-and-systems/03-energy-and-power.md
      - Chapter 4 - What is a System?: c1-signals-and-systems/m1-intro-to-signals-and-systems/04-what-is-a-system.md
    - Module 1.2 - LTI Systems:
      - Overview: c1-signals-and-systems/m2-lti-systems/overview.md
    - Module 1.2 - Frequency Domain Analysis:
      - Overview: c1-signals-and-systems/m3-frequency-domain-analysis/overview.md
    - Module 1.4 - Non-linear Systems:
      - Overview: c1-signals-and-systems/m4-non-linear-systems/overview.md
    - Module 1.5 - Intro to State-Space:
      - Overview: c1-signals-and-systems/m5-intro-to-state-space/overview.md
  - Control:
    - Module 2.1 - Intro to Control:
      - Overview: c2-control/m1-intro-to-control/overview.md
    - Module 2.2 - Open Loop Systems:
      - Overview: c2-control/m2-open-loop-systems/overview.md
    - Module 2.3 - Closed Loop Systems:
      - Overview: c2-control/m3-closed-loop-systems/overview.md
    - Module 2.4 - PID Control:
      - Overview: c2-control/m4-pid-control/overview.md
    - Module 2.5 - State Space Control:
      - Overview: c2-control/m5-state-space-control/overview.md
  - Robotics:
    - Module 3.1 - Intro to Robotics:
      - Overview: c3-robotics/m1-intro-to-robotics/overview.md
    - Module 3.2 - Rotations and Transformations:
      - Overview: c3-robotics/m2-rotations-and-transformations/overview.md
    - Module 3.3 - Configuration Space:
      - Overview: c3-robotics/m3-configuration-space/overview.md


markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true

extra_javascript:
  - js/mathjax-config.js              # your existing config for equations
  - https://polyfill.io/v3/polyfill.min.js?features=es6

  # ONE MathJax bundle is enough:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

  # Your own JS
  - js/quizzes.js
  - js/opencv-demos.js
  - js/repl.js

  # TikZJax (after everything else is fine)
  - https://tikzjax.com/v1/tikzjax.js


extra_css:
  - css/custom.css
  - https://tikzjax.com/v1/fonts.css   # <-- add this

  
plugins:
  - search
  - toggle-sidebar:
      theme: material
      toggle_button: navigation      # show one button controlling the nav
      show_navigation_by_default: true
      show_toc_by_default: true
      # optional: custom icon (defaults already to a hamburger)
      button_toggle_icon: >
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
          <path d="M3 6h18v2H3V6m0 5h18v2H3v-2m0 5h18v2H3v-2Z"></path>
        </svg>
